services:
  mc:
    container_name: minecraft-lobby
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "Foo§rBar"
      ONLINE_MODE: "FALSE"
      MEMORY: 1024M
      TYPE: PAPER



    volumes:
        - mc-data:/data
  mc-farmwelt:
    container_name: minecraft-farmwelt
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "Foo§rBar"
      ONLINE_MODE: "FALSE"
      TYPE: PAPER

    volumes:
        -  mc-farmwelt-data:/data

        
  minecraft-proxy:
    container_name: minecraft-proxy
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - 25565:25577
    volumes:
      - proxy-data:/server
